In [3]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt 
%matplotlib inline
import matplotlib
matplotlib.rcParams['figure.figsize'] = (20,10)

In [4]:
df = pd.read_csv('bengaluru_house_prices.csv')
df.head()

              area_type   availability                  location       size  society total_sqft  bath  balcony   price
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK  Coomee        1056   2.0      1.0   39.07
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom  Theanmp       2600   5.0      3.0  120.00
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK      NaN       1440   2.0      3.0   62.00
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK  Soiewre       1521   3.0      1.0   95.00
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK      NaN       1200   2.0      1.0   51.00

In [5]:
df.drop(['balcony','availability','area_type','society'],axis='columns',inplace=True)

In [6]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [7]:
df.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [8]:
df.shape

(13320, 5)

In [9]:
df.dropna(inplace=True)
df.shape

(13246, 5)

In [10]:
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [11]:
df['BHK'] =  df['size'].apply(lambda x: int(x.split(' ')[0]))
df.head()

                   location       size total_sqft  bath   price  BHK
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [12]:
df.bath.unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9.,  8.,  7., 11., 10., 14., 27.,
       12., 16., 40., 15., 13., 18.])

In [13]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [14]:
df[~df['total_sqft'].apply(is_float)].head()

               location   size   total_sqft  bath    price  BHK
30            Yelahanka  4 BHK  2100 - 2850   4.0  186.000    4
122              Hebbal  4 BHK  3067 - 8156   4.0  477.000    4
137  8th Phase JP Nagar  2 BHK  1042 - 1105   2.0   54.005    2
165            Sarjapur  2 BHK  1145 - 1340   2.0   43.490    2
188            KR Puram  2 BHK  1015 - 1540   2.0   56.800    2

In [15]:
def convert_num_total_sqft(x):
    try:
        tokens = str(x).split('-')   # str(x) handles NaN/float values safely
        if len(tokens) == 2:
            return (float(tokens[0]) + float(tokens[1])) / 2
        return float(x)
    except:
        return None  # handles anything non-convertible

df['total_sqft'] = df['total_sqft'].apply(convert_num_total_sqft)
df.dropna(subset=['total_sqft'], inplace=True)
df['total_sqft'].dtype  # should be float64 now

dtype('float64')

In [16]:
convert_num_total_sqft('2100-2800')

2450.0

In [17]:
df.total_sqft.apply(convert_num_total_sqft)

0        1056.0
1        2600.0
2        1440.0
3        1521.0
4        1200.0
          ...
13315    3453.0
13316    3600.0
13317    1141.0
13318    4689.0
13319     550.0
Name: total_sqft, Length: 13200, dtype: float64

In [18]:
df.total_sqft.unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [19]:
df['total_price_per_sqft'] = (df['price']*100000) / df['total_sqft']
df.head()

                   location       size  total_sqft  bath   price  BHK  total_price_per_sqft
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2           3699.810606
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4           4615.384615
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3           4305.555556
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3           6245.890861
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2           4250.000000

In [20]:
len(df.location.unique())

1298

In [21]:
df.location = df.location.apply(lambda x : x.strip())
location_state = df.groupby('location')['location'].agg('count')
location_state

location
1 Annasandrapalya                                  1
1 Giri Nagar                                       1
1 Immadihalli                                      1
1 Ramamurthy Nagar                                 1
12th cross srinivas nagar banshankari 3rd stage    1
                                                  ..
t.c palya                                          1
tc.palya                                           4
vinayakanagar                                      1
white field,kadugodi                               1
whitefiled                                         1
Name: location, Length: 1287, dtype: int64

In [22]:
state_less_than_10 = location_state[location_state<=10]
state_less_than_10

location
1 Annasandrapalya                                  1
1 Giri Nagar                                       1
1 Immadihalli                                      1
1 Ramamurthy Nagar                                 1
12th cross srinivas nagar banshankari 3rd stage    1
                                                  ..
t.c palya                                          1
tc.palya                                           4
vinayakanagar                                      1
white field,kadugodi                               1
whitefiled                                         1
Name: location, Length: 1047, dtype: int64

In [23]:
df.location = df.location.apply(lambda x :'other' if x in state_less_than_10 else x)
len(df.location.unique())

241

In [24]:
df.head()

                   location       size  total_sqft  bath   price  BHK  total_price_per_sqft
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2           3699.810606
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4           4615.384615
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3           4305.555556
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3           6245.890861
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2           4250.000000

In [25]:
df.shape

(13200, 7)

In [26]:
df = df[~(df.total_sqft / df.BHK < 300)]
df.shape

(12456, 7)

In [27]:
df.total_price_per_sqft.describe()

count     12456.000000
mean       6308.502826
std        4168.127339
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: total_price_per_sqft, dtype: float64

In [28]:
def outlier_ppp_removel(df):
    df_out = pd.DataFrame()
    for key,subdf in df.groupby('location'):
        m = np.mean(subdf.total_price_per_sqft)
        sd = np.std(subdf.total_price_per_sqft)
        reduce_df = subdf[(subdf.total_price_per_sqft>(m-sd)) & (subdf.total_price_per_sqft<=(m+sd))]
        df_out = pd.concat([df_out,reduce_df],ignore_index=False)

    return df_out

df = outlier_ppp_removel(df)
df.shape

(10242, 7)

In [29]:
def remove_bhk_outliers(df):
    exclude_indices = np.array([])
    
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        
        for bhk, bhk_df in location_df.groupby('BHK'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.total_price_per_sqft),
                'std': np.std(bhk_df.total_price_per_sqft),
                'count': bhk_df.shape[0]
            }
        
        for bhk, bhk_df in location_df.groupby('BHK'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.total_price_per_sqft < (stats['mean'])].index.values
                )
    
    return df.drop(exclude_indices, axis='index')

df = remove_bhk_outliers(df)
df.shape

(7317, 7)

In [30]:
df = df[df.bath<df.BHK+2] 
df.shape

(7239, 7)

In [31]:
df.drop(['size','total_price_per_sqft'],axis='columns')

                  location  total_sqft  bath  price  BHK
210    1st Block Jayanagar      2850.0   4.0  428.0    4
848    1st Block Jayanagar      1630.0   3.0  194.0    3
2152   1st Block Jayanagar      1875.0   2.0  235.0    3
7138   1st Block Jayanagar      1200.0   2.0  130.0    3
7358   1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
13238                other      1200.0   2.0   70.0    2
13245                other      1800.0   1.0  200.0    1
13285                other      1353.0   2.0  110.0    2
13291                other       812.0   1.0   26.0    1
13316                other      3600.0   5.0  400.0    4

[7239 rows x 5 columns]

dummies = pd.get_dummies(df.location)
dummies

In [32]:
dummies = pd.get_dummies(df.location)
dummies

       1st Block Jayanagar  1st Phase JP Nagar  2nd Phase Judicial Layout  ...  Yelenahalli  Yeshwanthpur  other
210                   True               False                      False  ...        False         False  False
848                   True               False                      False  ...        False         False  False
2152                  True               False                      False  ...        False         False  False
7138                  True               False                      False  ...        False         False  False
7358                  True               False                      False  ...        False         False  False
...                    ...                 ...                        ...  ...          ...           ...    ...
13238                False               False                      False  ...        False         False   True
13245                False               False                      False  ...        False         False   True
13285                False               False                      False  ...        False         False   True
13291                False               False                      False  ...        False         False   True
13316                False               False                      False  ...        False         False   True

[7239 rows x 241 columns]

KeyError: "['1st Block Jayanagar', '1st Phase JP Nagar', '2nd Phase Judicial Layout', '2nd Stage Nagarbhavi', '5th Block Hbr Layout', '5th Phase JP Nagar', '6th Phase JP Nagar', '7th Phase JP Nagar', '8th Phase JP Nagar', '9th Phase JP Nagar', 'AECS Layout', 'Abbigere', 'Akshaya Nagar', 'Ambalipura', 'Ambedkar Nagar', 'Amruthahalli', 'Anandapura', 'Ananth Nagar', 'Anekal', 'Anjanapura', 'Ardendale', 'Arekere', 'Attibele', 'BEML Layout', 'BTM 2nd Stage', 'BTM Layout', 'Babusapalaya', 'Badavala Nagar', 'Balagere', 'Banashankari', 'Banashankari Stage II', 'Banashankari Stage III', 'Banashankari Stage V', 'Banashankari Stage VI', 'Banaswadi', 'Banjara Layout', 'Bannerghatta', 'Bannerghatta Road', 'Basavangudi', 'Basaveshwara Nagar', 'Battarahalli', 'Begur', 'Begur Road', 'Bellandur', 'Benson Town', 'Bharathi Nagar', 'Bhoganhalli', 'Billekahalli', 'Binny Pete', 'Bisuvanahalli', 'Bommanahalli', 'Bommasandra', 'Bommasandra Industrial Area', 'Bommenahalli', 'Brookefield', 'Budigere', 'CV Raman Nagar', 'Chamrajpet', 'Chandapura', 'Channasandra', 'Chikka Tirupathi', 'Chikkabanavar', 'Chikkalasandra', 'Choodasandra', 'Cooke Town', 'Cox Town', 'Cunningham Road', 'Dasanapura', 'Dasarahalli', 'Devanahalli', 'Devarachikkanahalli', 'Dodda Nekkundi', 'Doddaballapur', 'Doddakallasandra', 'Doddathoguru', 'Domlur', 'Dommasandra', 'EPIP Zone', 'Electronic City', 'Electronic City Phase II', 'Electronics City Phase 1', 'Frazer Town', 'GM Palaya', 'Garudachar Palya', 'Giri Nagar', 'Gollarapalya Hosahalli', 'Gottigere', 'Green Glen Layout', 'Gubbalala', 'Gunjur', 'HAL 2nd Stage', 'HBR Layout', 'HRBR Layout', 'HSR Layout', 'Haralur Road', 'Harlur', 'Hebbal', 'Hebbal Kempapura', 'Hegde Nagar', 'Hennur', 'Hennur Road', 'Hoodi', 'Horamavu Agara', 'Horamavu Banaswadi', 'Hormavu', 'Hosa Road', 'Hosakerehalli', 'Hoskote', 'Hosur Road', 'Hulimavu', 'ISRO Layout', 'ITPL', 'Iblur Village', 'Indira Nagar', 'JP Nagar', 'Jakkur', 'Jalahalli', 'Jalahalli East', 'Jigani', 'Judicial Layout', 'KR Puram', 'Kadubeesanahalli', 'Kadugodi', 'Kaggadasapura', 'Kaggalipura', 'Kaikondrahalli', 'Kalena Agrahara', 'Kalyan nagar', 'Kambipura', 'Kammanahalli', 'Kammasandra', 'Kanakapura', 'Kanakpura Road', 'Kannamangala', 'Karuna Nagar', 'Kasavanhalli', 'Kasturi Nagar', 'Kathriguppe', 'Kaval Byrasandra', 'Kenchenahalli', 'Kengeri', 'Kengeri Satellite Town', 'Kereguddadahalli', 'Kodichikkanahalli', 'Kodigehaali', 'Kodigehalli', 'Kodihalli', 'Kogilu', 'Konanakunte', 'Koramangala', 'Kothannur', 'Kothanur', 'Kudlu', 'Kudlu Gate', 'Kumaraswami Layout', 'Kundalahalli', 'LB Shastri Nagar', 'Laggere', 'Lakshminarayana Pura', 'Lingadheeranahalli', 'Magadi Road', 'Mahadevpura', 'Mahalakshmi Layout', 'Mallasandra', 'Malleshpalya', 'Malleshwaram', 'Marathahalli', 'Margondanahalli', 'Marsur', 'Mico Layout', 'Munnekollal', 'Murugeshpalya', 'Mysore Road', 'NGR Layout', 'NRI Layout', 'Nagarbhavi', 'Nagasandra', 'Nagavara', 'Nagavarapalya', 'Narayanapura', 'Neeladri Nagar', 'Nehru Nagar', 'OMBR Layout', 'Old Airport Road', 'Old Madras Road', 'Padmanabhanagar', 'Pai Layout', 'Panathur', 'Parappana Agrahara', 'Pattandur Agrahara', 'Poorna Pragna Layout', 'Prithvi Layout', 'R.T. Nagar', 'Rachenahalli', 'Raja Rajeshwari Nagar', 'Rajaji Nagar', 'Rajiv Nagar', 'Ramagondanahalli', 'Ramamurthy Nagar', 'Rayasandra', 'Sahakara Nagar', 'Sanjay nagar', 'Sarakki Nagar', 'Sarjapur', 'Sarjapur  Road', 'Sarjapura - Attibele Road', 'Sector 2 HSR Layout', 'Sector 7 HSR Layout', 'Seegehalli', 'Shampura', 'Shivaji Nagar', 'Singasandra', 'Somasundara Palya', 'Sompura', 'Sonnenahalli', 'Subramanyapura', 'Sultan Palaya', 'TC Palaya', 'Talaghattapura', 'Thanisandra', 'Thigalarapalya', 'Thubarahalli', 'Tindlu', 'Tumkur Road', 'Ulsoor', 'Uttarahalli', 'Varthur', 'Varthur Road', 'Vasanthapura', 'Vidyaranyapura', 'Vijayanagar', 'Vishveshwarya Layout', 'Vishwapriya Layout', 'Vittasandra', 'Whitefield', 'Yelachenahalli', 'Yelahanka', 'Yelahanka New Town', 'Yelenahalli', 'Yeshwanthpur', 'other'] not found in axis"

In [34]:
df

                  location       size  total_sqft  bath  price  BHK  total_price_per_sqft
210    1st Block Jayanagar      4 BHK      2850.0   4.0  428.0    4          15017.543860
848    1st Block Jayanagar      3 BHK      1630.0   3.0  194.0    3          11901.840491
2152   1st Block Jayanagar      3 BHK      1875.0   2.0  235.0    3          12533.333333
7138   1st Block Jayanagar      3 BHK      1200.0   2.0  130.0    3          10833.333333
7358   1st Block Jayanagar      2 BHK      1235.0   2.0  148.0    2          11983.805668
...                    ...        ...         ...   ...    ...  ...                   ...
13238                other      2 BHK      1200.0   2.0   70.0    2           5833.333333
13245                other      1 BHK      1800.0   1.0  200.0    1          11111.111111
13285                other      2 BHK      1353.0   2.0  110.0    2           8130.081301
13291                other  1 Bedroom       812.0   1.0   26.0    1           3201.970443
13316                other      4 BHK      3600.0   5.0  400.0    4          11111.111111

[7239 rows x 7 columns]

In [35]:
df1 = pd.concat([df,dummies.drop('other',axis='columns')],axis='columns')

In [36]:
df1.head(3)

                 location   size  total_sqft  bath  ...  Yelahanka  Yelahanka New Town  Yelenahalli  Yeshwanthpur
210   1st Block Jayanagar  4 BHK      2850.0   4.0  ...      False               False        False         False
848   1st Block Jayanagar  3 BHK      1630.0   3.0  ...      False               False        False         False
2152  1st Block Jayanagar  3 BHK      1875.0   2.0  ...      False               False        False         False

[3 rows x 247 columns]

In [37]:
df1 = df1.drop('location',axis='columns')
df1.head(3)

       size  total_sqft  bath  price  BHK  ...  Yelachenahalli  Yelahanka  Yelahanka New Town  Yelenahalli  Yeshwanthpur
210   4 BHK      2850.0   4.0  428.0    4  ...           False      False               False        False         False
848   3 BHK      1630.0   3.0  194.0    3  ...           False      False               False        False         False
2152  3 BHK      1875.0   2.0  235.0    3  ...           False      False               False        False         False

[3 rows x 246 columns]

In [38]:
X = df1.drop(['price','total_price_per_sqft','size'],axis='columns')
X

       total_sqft  bath  BHK  1st Block Jayanagar  ...  Yelahanka  Yelahanka New Town  Yelenahalli  Yeshwanthpur
210        2850.0   4.0    4                 True  ...      False               False        False         False
848        1630.0   3.0    3                 True  ...      False               False        False         False
2152       1875.0   2.0    3                 True  ...      False               False        False         False
7138       1200.0   2.0    3                 True  ...      False               False        False         False
7358       1235.0   2.0    2                 True  ...      False               False        False         False
...           ...   ...  ...                  ...  ...        ...                 ...          ...           ...
13238      1200.0   2.0    2                False  ...      False               False        False         False
13245      1800.0   1.0    1                False  ...      False               False        False         False
13285      1353.0   2.0    2                False  ...      False               False        False         False
13291       812.0   1.0    1                False  ...      False               False        False         False
13316      3600.0   5.0    4                False  ...      False               False        False         False

[7239 rows x 243 columns]

In [39]:
y = df.price
y

210      428.0
848      194.0
2152     235.0
7138     130.0
7358     148.0
         ...
13238     70.0
13245    200.0
13285    110.0
13291     26.0
13316    400.0
Name: price, Length: 7239, dtype: float64

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [42]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8629132245229441

In [43]:
from sklearn.model_selection import cross_val_score, ShuffleSplit

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores = cross_val_score(LinearRegression(), X, y, cv=cv, scoring='r2')
print(scores)
print("Mean R2:", scores.mean())

[0.82702546 0.86027005 0.85322178 0.8436466  0.85481502]
Mean R2: 0.8477957812447519

In [53]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

In [57]:
def find_best_model(X,y):
    algos = {
        'Linear Regression' : {
            'model' : LinearRegression(),
            'params' : {
                
            }
        },
        'Lasso' : {
            'model' : Lasso(),
            'params' : {
                'alpha' : [1,2],
                'selection' : ['random','cyclic']
            }
        },
        'Decision Tree' : {
            'model' : DecisionTreeRegressor(),
            'params' : {
                'splitter' : ['best','random'],
                'criterion' : ['squared_error','friedman_mse']
            }
        }
    }

    scores = []
    cv = ShuffleSplit(n_splits=5,test_size=0.2,random_state=False)
    for algo_name,config in algos.items():
        grid = GridSearchCV(config['model'],config['params'],cv=cv,return_train_score=False)
        grid.fit(X,y)
        scores.append(
           { 'model': algo_name,
            'Best Score' : grid.best_score_,
            'Best Params' : grid.best_params_  
    })

    return pd.DataFrame(scores,columns=['model','Best Score','Best Params'])

find_best_model(X,y)

               model  Best Score                                        Best Params
0  Linear Regression    0.847796                                                 {}
1              Lasso    0.726768                {'alpha': 2, 'selection': 'random'}
2      Decision Tree    0.712662  {'criterion': 'friedman_mse', 'splitter': 'best'}

In [70]:
def Predict_price(location,sqft,bath,bhk):
    loc_idx = np.where(X.columns==location)[0][0]

    x = np.zeros(len(X.columns))
    x[0] = sqft
    x[1] = bath
    x[2] = bhk

    if loc_idx >= 0:
        x[loc_idx] = 1

        

    return model.predict([x])

In [71]:
X.columns

Index(['total_sqft', 'bath', 'BHK', '1st Block Jayanagar',
       '1st Phase JP Nagar', '2nd Phase Judicial Layout',
       '2nd Stage Nagarbhavi', '5th Block Hbr Layout', '5th Phase JP Nagar',
       '6th Phase JP Nagar',
       ...
       'Vijayanagar', 'Vishveshwarya Layout', 'Vishwapriya Layout',
       'Vittasandra', 'Whitefield', 'Yelachenahalli', 'Yelahanka',
       'Yelahanka New Town', 'Yelenahalli', 'Yeshwanthpur'],
      dtype='object', length=243)

In [72]:
loc_idx = np.where(X.columns=='Vijayanagar')[0][0]
loc_idx

np.int64(233)

In [73]:
Predict_price('1st Phase JP Nagar',1000,2,2)

C:\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([83.86570258])

In [74]:
Predict_price('1st Phase JP Nagar',1000,3,2)

C:\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([87.58264929])

In [75]:
import pickle

with open('House_Price_Prediction_Model.pickle','wb') as f:
    pickle.dump(model,f)

In [82]:
import json 

columns1 = {
    'data_columns' : [col.lower() for col in X.columns]
}

with open('columns.json','w') as f:
    f.write(json.dumps(columns1))